package POJO;
// Generated 1 Aug, 2023 10:22:10 PM by Hibernate Tools 4.3.1



/**
 * Studenttb generated by hbm2java
 */
public class Studenttb  implements java.io.Serializable {


     private Integer id;
     private String sfname;
     private String slname;
     private String sdob;
     private String semail;
     private int smobile;
     private String saddress;
     private String scity;
     private String sstate;
     private int szip;
     private String sadmissionno;
     private String scourse;
     private String scoursedepartment;

    public Studenttb() {
    }

    public Studenttb(String sfname, String slname, String sdob, String semail, int smobile, String saddress, String scity, String sstate, int szip, String sadmissionno, String scourse, String scoursedepartment) {
       this.sfname = sfname;
       this.slname = slname;
       this.sdob = sdob;
       this.semail = semail;
       this.smobile = smobile;
       this.saddress = saddress;
       this.scity = scity;
       this.sstate = sstate;
       this.szip = szip;
       this.sadmissionno = sadmissionno;
       this.scourse = scourse;
       this.scoursedepartment = scoursedepartment;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSfname() {
        return this.sfname;
    }
    
    public void setSfname(String sfname) {
        this.sfname = sfname;
    }
    public String getSlname() {
        return this.slname;
    }
    
    public void setSlname(String slname) {
        this.slname = slname;
    }
    public String getSdob() {
        return this.sdob;
    }
    
    public void setSdob(String sdob) {
        this.sdob = sdob;
    }
    public String getSemail() {
        return this.semail;
    }
    
    public void setSemail(String semail) {
        this.semail = semail;
    }
    public int getSmobile() {
        return this.smobile;
    }
    
    public void setSmobile(int smobile) {
        this.smobile = smobile;
    }
    public String getSaddress() {
        return this.saddress;
    }
    
    public void setSaddress(String saddress) {
        this.saddress = saddress;
    }
    public String getScity() {
        return this.scity;
    }
    
    public void setScity(String scity) {
        this.scity = scity;
    }
    public String getSstate() {
        return this.sstate;
    }
    
    public void setSstate(String sstate) {
        this.sstate = sstate;
    }
    public int getSzip() {
        return this.szip;
    }
    
    public void setSzip(int szip) {
        this.szip = szip;
    }
    public String getSadmissionno() {
        return this.sadmissionno;
    }
    
    public void setSadmissionno(String sadmissionno) {
        this.sadmissionno = sadmissionno;
    }
    public String getScourse() {
        return this.scourse;
    }
    
    public void setScourse(String scourse) {
        this.scourse = scourse;
    }
    public String getScoursedepartment() {
        return this.scoursedepartment;
    }
    
    public void setScoursedepartment(String scoursedepartment) {
        this.scoursedepartment = scoursedepartment;
    }




}


